/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "android/log.h"

/* Header for class com_linecutfeng_lowpoly_Sobel */
#define TAG "icv_jni" // 这个是自定义的LOG的标识
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__) // 定义LOGI类型

/* Header for class com_linecutfeng_lowpoly_Delaunay */

static const float EPSILON = 1.0f / 1048576.0f;

#ifndef _Included_com_linecutfeng_lowpoly_Delaunay
#define _Included_com_linecutfeng_lowpoly_Delaunay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linecutfeng_lowpoly_Delaunay
 * Method:    triangulateFromNative
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_linecutfeng_lowpoly_Delaunay_triangulateFromNative
        (JNIEnv *, jclass, jobject);


class Circumcircle {
public :
    int i, j, k;
    float x, y, r;

    Circumcircle(int i, int j, int k, float x, float y, float r) : i(i), j(j), k(k), x(x), y(y),
                                                                   r(r) {}
    ~Circumcircle(){}
};

#ifdef __cplusplus
}
#endif
#endif
