/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codepig_ffmpegcldemo_FFmpegKit */

#ifndef _Included_codepig_ffmpegcldemo_FFmpegKit
#define _Included_codepig_ffmpegcldemo_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codepig_ffmpegcldemo_FFmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codepig_ffmpegcldemo_FFmpegKit_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
